### ISSUE TITLE
Config geändert aber alte Werte

### ISSUE THREAD

**Issue by davidhellmann** [martinherweg/craft3-gonzo#9]
Hab die Description geändert aber er holt sich immer noch den alten Wert. Dist ist auch alles richtig.

**Comment by davidhellmann** [comment]
OK war wohl nen dreckiger DIST Folder :D

**Comment by davidhellmann** [comment]
Wenn ich aber Werte in der Config ändere tauchen die Sachen in der Sidebar dann doppelt auf:

![image](https://user-images.githubusercontent.com/764292/35895689-d53ba78a-0bb8-11e8-83b2-87b80ab95b8c.png)

**Comment by martinherweg** [comment]
Ich glaube deine doppelte Headline ist ein falsches config file und kein Doppelter Content, check mal bitte die config der "subline" Komponente
